[package]
name = "algo_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
# On ne pr√©cise pas la version, on dit juste de regarder le workspace
env_lib = { workspace = true }
rand = { workspace = true }
